import { ApplicationConfig, provideZoneChangeDetection } from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideFirebaseApp, initializeApp } from '@angular/fire/app';
import { provideFirestore, getFirestore } from '@angular/fire/firestore';
import { provideAuth, getAuth } from '@angular/fire/auth';
import { routes } from './app.routes';
import { environment } from '../environments/environment';
import { provideStorage, getStorage } from '@angular/fire/storage';
import { provideHttpClient, withXhr } from '@angular/common/http';

// ✅ IMPORTAR NG ICONS
import { provideIcons } from '@ng-icons/core';
import {
  heroHeart,
  heroCalendar,
  heroMapPin,
  heroArrowDown,
  heroClock,
  heroMap,
  heroSparkles,
  heroCheckBadge,
  heroBookOpen,
  heroCamera,
  heroCheck,
  heroUsers,
  heroGift,
  heroCalendarDays,
  heroHashtag,
  heroStar,
  heroShare,
  heroTag,
  heroHandRaised,
  heroTrash,
  heroExclamationCircle,
  heroPlusCircle,
  heroArrowRight,
  heroHome,
  heroPencil,
  heroCheckCircle,
  heroXCircle,
  heroUserCircle,
  heroTicket,
  heroChatBubbleLeft,
  heroBolt,
  heroXMark,
  heroPhoto,
  heroDevicePhoneMobile,
  heroComputerDesktop,
  heroInformationCircle,
  heroCake,
  heroPlay,
  heroMagnifyingGlass,
  heroPaintBrush,
  heroEye,
  heroSquares2x2,
  heroDocumentText,
  heroDocument,
  heroPlus,
  heroBuildingOffice,
  heroGlobeAmericas,
  heroLightBulb,
  heroSquaresPlus,
  heroArrowLongRight,
  heroCog6Tooth,
  heroAdjustmentsHorizontal,
  heroChevronLeft,
  heroEllipsisHorizontal,
  heroListBullet,
  heroCube,
  heroBanknotes,
  heroArrowPath,
  heroExclamationTriangle,
  heroUser,
} from '@ng-icons/heroicons/outline';
//Lucide icons
import {
  lucideChurch,
  lucideSparkles,
  lucideArrowBigDown,
  lucideHeartCrack,
  lucideHourglass,
  lucideBan,
  lucideCrown,
  lucideCar,
  lucideCheckCheck,
  lucideClipboard,
  lucideBaby,
  lucideEye,
  lucideSmartphone,
  lucideParkingCircle,
  lucidePin,
  lucideMail,
  lucideFeather,
  lucideTarget,
  lucideTrash2,
  lucideLink,
  lucideCloud,
  lucideSwatchBook,
  lucideRuler,
  lucideArrowLeftRight,
  lucideBanknoteArrowUp,
  lucideShoppingBag,
  lucideFlower2,
} from '@ng-icons/lucide';
//Huge Icons
import {
  hugeBulb,
  hugeAirbnb,
  hugeSuit02,
  hugeStar,
  hugePhoneOff01,
  hugeDiamond02,
  hugeQrCode,
  hugeWhatsapp,
  hugeUserGroup,
  hugeUserAdd02,
  hugeRainbow,
  hugeTextFont,
} from '@ng-icons/huge-icons';
// Phosphor Icons
import {
  phosphorFlowerTulip,
  phosphorFlower,
  phosphorFlowerLotus,
} from '@ng-icons/phosphor-icons/regular';
import { phosphorDoorOpen } from '@ng-icons/phosphor-icons/regular';
import { phosphorHandWaving } from '@ng-icons/phosphor-icons/regular';

export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes),
    provideStorage(() => getStorage()),
    provideHttpClient(withXhr()),
    provideFirebaseApp(() => initializeApp(environment.firebaseConfig)),
    provideFirestore(() => getFirestore()),
    provideAuth(() => getAuth()),

    // ✅ AGREGAR NG ICONS
    provideIcons({
      //Heroicons
      heroHeart,
      heroCalendar,
      heroMapPin,
      heroArrowDown,
      heroClock, //
      heroMap, //
      heroSparkles, //
      heroCheckBadge,
      heroBookOpen,
      heroCamera,
      heroCheck,
      heroUsers,
      heroGift,
      heroCalendarDays,
      heroHashtag,
      heroStar,
      heroShare,
      heroTag,
      heroHandRaised,
      heroTrash,
      heroExclamationCircle,
      heroPlusCircle,
      heroArrowRight,
      heroHome,
      heroPencil,
      heroCheckCircle,
      heroXCircle,
      heroUserCircle,
      heroTicket,
      heroChatBubbleLeft,
      heroBolt,
      heroPhoto,
      heroXMark,
      heroDevicePhoneMobile,
      heroComputerDesktop,
      heroInformationCircle,
      heroCake,
      heroPlay,
      heroMagnifyingGlass,
      heroPaintBrush,
      heroEye,
      heroSquares2x2,
      heroDocumentText,
      heroDocument,
      heroPlus,
      heroBuildingOffice,
      heroGlobeAmericas,
      heroLightBulb,
      heroSquaresPlus,
      heroArrowLongRight,
      heroCog6Tooth,
      heroAdjustmentsHorizontal,
      heroChevronLeft,
      heroEllipsisHorizontal,
      heroListBullet,
      heroCube,
      heroBanknotes,
      heroArrowPath,
      heroExclamationTriangle,
      heroUser,

      //Lucide Icons
      lucideChurch,
      lucideSparkles,
      lucideArrowBigDown,
      lucideHeartCrack,
      lucideHourglass,
      lucideBan,
      lucideCrown,
      lucideCar,
      lucideCheckCheck,
      lucideClipboard,
      lucideBaby,
      lucideEye,
      lucideSmartphone,
      lucideParkingCircle,
      lucidePin,
      lucideMail,
      lucideFeather,
      lucideTarget,
      lucideTrash2,
      lucideLink,
      lucideCloud,
      lucideSwatchBook,
      lucideRuler,
      lucideArrowLeftRight,
      lucideBanknoteArrowUp,
      lucideShoppingBag,
      lucideFlower2,

      //Huge Icons
      hugeBulb,
      hugeAirbnb,
      hugeSuit02,
      hugeStar,
      hugePhoneOff01,
      hugeDiamond02,
      hugeQrCode,
      hugeWhatsapp,
      hugeUserGroup,
      hugeUserAdd02,
      hugeRainbow,
      hugeTextFont,

      //Phosphor Icons
      phosphorFlowerTulip,
      phosphorFlower,
      phosphorFlowerLotus,
      phosphorDoorOpen,
      phosphorHandWaving,
    }),
  ],
};
